export const ADMIN_ROUTE = "/admin";
export const ANNOUNCE_ROUTE = "/announce";
export const REGISTRATION_ROUTE = "/registration";
export const LOGIN_ROUTE = "/login";
// export const EMPLOYEE_PORTFOLIO_ROUTE = "/employee/:id";
export const EMPLOYEE_LIST_ROUTE = "/employee";
export const EVENT_ROUTE = "/event";
export const MAIN_ROUTE = "/";
export const ORDER_ROUTE = "/order";
